### ISSUE TITLE
TomTom start 25 

### ISSUE THREAD

**Issue by Bakir0-dev** [navit-gps/NavitTom#11]
I cant mount my tomtom as a drive neither when I insert SD card it doesnt want to override the main OS and I dont have navit in there as a app or as a system, what do I do, tt only appears as network adapter

**Comment by CodeAsm** [comment]
I think thats a very recent Tomtom device, unsure if hackable at the moment.
My father has one of those modern new ones and I was curious to see how TomTom updates their devices these days, appears to use a network device to "securly" communicate over this new network device and dont expose the internal or sd card to the pc. 
I think they run Linux these days by default but using the network and the PC side application and maybe a VPN tunnel will maybe prevent us from (easely) hacking modern tomtom devices. There is a recovery mode however, unsure if that can expose something else, also dint opened the device for jtag or debugging ports.

Unsure if the contents of the SD can be altered to make the system boot from there either.
