### ISSUE TITLE
arm-linux-gcc: Command not found

### ISSUE THREAD

**Issue by PedroMiguelCarraro** [navit-gps/NavitTom#12]
Hello, for the last couple of days I've been trying to compile NavitTom from the binaries,
I did as the README.md file said,

Install the following dependencies: subversion chrpath fluid imagemagick xsltproc
Set the ROOT envvar in get_cross_env.sh
source get_cross_env.sh
Run make to start the initial OpenTom build

but the make keep breaking, with the mensage
Make[1]:  arm-linux-gcc: Command not found
and I don't know what to do,

I'm compiling in a Ubuntu VM, and here are the Makefile, the Kernel.log, and the terminal Error mesage for make

[Makefile.txt](https://github.com/navit-gps/NavitTom/files/7842344/Makefile.txt)
[kernel.log](https://github.com/navit-gps/NavitTom/files/7842354/kernel.log)
[terminal.txt](https://github.com/navit-gps/NavitTom/files/7842357/terminal.txt)

    user@user:~/Desktop/navittom$ make

test -d gcc-3.3.4_glibc-2.3.2/lib || { \
	tar xf /home/user/Desktop/navittom/Downloads/toolchain_redhat_gcc-3.3.4_glibc-2.3.2-20060131a.tar.gz; \
	cd gcc-3.3.4_glibc-2.3.2/arm-linux/ && { \
		mv sys-root sys-root.orig; \
		ln -s sys-root.orig libc; \
		ln -s /home/user/Desktop/navittom/arm-sysroot/ sys-root; \
	}; \
	cd /home/user/Desktop/navittom/gcc-3.3.4_glibc-2.3.2/bin && cat /home/user/Desktop/navittom/configs/install_links.txt | while read file; do ln -s $file; done; \
}
mkdir -p /home/user/Desktop/navittom/logs
cd kernel && make clean && nice -n 19 make -j6 >/home/user/Desktop/navittom/logs/kernel.log 2>&1
make[1]: Entering directory '/home/user/Desktop/navittom/src/linux-s3c24xx'
make[1]: arm-linux-gcc: Command not found
make[3]: arm-linux-gcc: Command not found
  CLEAN   .tmp_versions
  CLEAN   include/asm-arm/arch include/asm-arm/.arch
make[1]: Leaving directory '/home/user/Desktop/navittom/src/linux-s3c24xx'
make: *** [Makefile:111: kernel/arch/arm/boot/zImage] Error 2

    user@user:~/Desktop/navittom$

**Comment by jkoan** [comment]
I think i ant reproduce what you did, but the last time i checked this setup worked:
https://github.com/navit-gps/NavitTom/blob/master/.circleci/config.yml
Just take a look at jobs->build->steps and there the run->commands from top to bottom. The CI is using Ubuntu 18.04 for that.
The Command not found should be because the toolchain is not setup correctly.

**Comment by PedroMiguelCarraro** [comment]
It's working, thank you,
I tried in 18.04 with run->commands and the arm-linux-gg was found, after that all went right,
the only thing was the http request for the expat-2.1.0.tar.gz in sourceforge returned error 404, for this I went to the github releases and download the expat-2.1.0.tar.gz and put on $ROOT/Downloads and run make again, now everithing is fine,
Thank you again for the help
